package com.marketdesk;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.*;
public class WidgetPresentationTest {
 @Test public void combinedFooterLeavesRoomForFourthRow(){Map<String,Object> saved=new HashMap<>();saved.put("watch","甲|Y:AAPL\n乙|Y:QQQ\n丙|Y:^NDX\n丁|E:1.518880");assertEquals(4,WidgetPresentation.rows(saved,256,0).size());assertEquals(3,WidgetPresentation.rows(saved,255,0).size());assertEquals("E:1.518880",WidgetPresentation.rows(saved,256,0).get(3).code);}
 @Test public void renamingKeepsQuoteForTheSameCode(){Map<String,Object> saved=new HashMap<>();saved.put("watch","旧名称|Y:AAPL");saved.put("Y:AAPL","{\"price\":123,\"change\":1,\"received\":1000}");saved.put("watch","新名称|Y:AAPL");WidgetPresentation.Row r=WidgetPresentation.rows(saved,316,1000).get(0);assertEquals("新名称",r.name);assertEquals("Y:AAPL",r.code);assertEquals("123.000",r.price);}
 @Test public void changingCodeDoesNotReuseOldSymbolsQuote(){Map<String,Object> saved=new HashMap<>();saved.put("watch","腾讯|Y:0700.HK");saved.put("Y:AAPL","{\"price\":123,\"change\":1}");WidgetPresentation.Row r=WidgetPresentation.rows(saved,316,1000).get(0);assertEquals("Y:0700.HK",r.code);assertEquals("—",r.price);assertEquals("暂不可用",r.meta);}
 @Test public void sameSnapshotProducesSamePreviewAndWidgetRows(){Map<String,Object> saved=new HashMap<>();saved.put("watch","自定义名称|E:1.561380");saved.put("E:1.561380","{\"price\":0.672,\"change\":-0.44,\"time\":\"09-30 日线\",\"received\":1000}");WidgetPresentation.Row widget=WidgetPresentation.rows(saved,316,1000).get(0),preview=WidgetPresentation.rows(saved,316,1000).get(0);assertEquals(widget.name,preview.name);assertEquals(widget.code,preview.code);assertEquals(widget.price,preview.price);assertEquals(widget.change,preview.change);assertEquals(widget.meta,preview.meta);assertEquals(widget.color,preview.color);}
 @Test public void fifthWatchIsNotDroppedAtReportedWidgetHeight(){Map<String,Object> saved=new HashMap<>();saved.put("watch","纳斯达克100|Y:^NDX\n纳斯达克|Y:^IXIC\n恒生科技|Y:HSTECH.HK\n创新药|E:2.931250\n国泰电网ETF|E:1.561380");List<WidgetPresentation.Row> rows=WidgetPresentation.rows(saved,316,10000);assertEquals(5,rows.size());assertEquals("E:1.561380",rows.get(4).code);}
 @Test public void heightLimitsSameOrderedList(){Map<String,Object> saved=new HashMap<>();saved.put("watch","甲|Y:AAPL\n乙|Y:QQQ\n丙|E:2.931250");List<WidgetPresentation.Row> rows=WidgetPresentation.rows(saved,208,10000);assertEquals(2,rows.size());assertEquals("Y:AAPL",rows.get(0).code);assertEquals("Y:QQQ",rows.get(1).code);}
 @Test public void smallAndLargeWidgetsHaveBoundedCapacity(){assertEquals(1,WidgetPresentation.capacity(100));assertEquals(20,WidgetPresentation.capacity(1000));}
 @Test public void resizingExpandsAndShrinksTheSameWatchlist(){Map<String,Object> saved=new HashMap<>();StringBuilder watch=new StringBuilder();for(int i=0;i<12;i++){if(i>0)watch.append('\n');watch.append("标的").append(i).append("|Y:TEST").append(i);}saved.put("watch",watch.toString());assertEquals(2,WidgetPresentation.rows(saved,208,0).size());assertEquals(5,WidgetPresentation.rows(saved,316,0).size());assertEquals(10,WidgetPresentation.rows(saved,520,0).size());assertEquals(2,WidgetPresentation.rows(saved,208,0).size());}
 @Test public void tallWidgetDoesNotCreateRowsBeyondSavedItems(){Map<String,Object> saved=new HashMap<>();saved.put("watch","苹果|Y:AAPL\n腾讯|Y:0700.HK");assertEquals(2,WidgetPresentation.rows(saved,1000,0).size());}
 @Test public void formatsTimePriceAndCacheFromSameSnapshot(){Map<String,Object> saved=new HashMap<>();saved.put("watch","指数|E:2.931250");saved.put("E:2.931250","{\"price\":1243.61,\"change\":4.12,\"time\":\"09-30 15:00\",\"kind\":\"minute\",\"dataTime\":1000,\"received\":1000}");saved.put("error:E:2.931250","失败");WidgetPresentation.Row r=WidgetPresentation.rows(saved,280,100000000).get(0);assertEquals("1243.610",r.price);assertEquals("+4.12%",r.change);assertEquals("09-30 15:00 历史 分时 缓存",r.meta);}
 @Test public void fundEstimatesAreMarked(){Map<String,Object> saved=new HashMap<>();saved.put("watch","基金|F:000001");saved.put("F:000001","{\"price\":1.5,\"change\":-1,\"time\":\"今天\",\"received\":1000}");WidgetPresentation.Row r=WidgetPresentation.rows(saved,280,1000).get(0);assertTrue(r.meta.endsWith("估算"));assertEquals("-1.00%",r.change);assertEquals(0xff41d399,r.color);}
 @Test public void badCacheDoesNotBecomeZeroQuote(){Map<String,Object> saved=new HashMap<>();saved.put("watch","苹果|Y:AAPL");saved.put("Y:AAPL","bad");WidgetPresentation.Row r=WidgetPresentation.rows(saved,280,0).get(0);assertEquals("—",r.price);assertEquals("暂不可用",r.meta);}
 @Test public void savingNewOrderIsReflected(){Map<String,Object> saved=new HashMap<>();saved.put("watch","甲|Y:AAPL\n乙|Y:QQQ");assertEquals("甲",WidgetPresentation.rows(saved,280,0).get(0).name);saved.put("watch","乙改名|Y:QQQ\n甲|Y:AAPL");assertEquals("乙改名",WidgetPresentation.rows(saved,280,0).get(0).name);}
}
